### ISSUE TITLE
Asking for Help with USB problem

### ISSUE THREAD

**Issue by scemama** [VanIseghemThomas/OpenCortex#9]
Hi!
First of all, thanks for your work, this is a very nice project!

I am contacting you because on the QC there is a severe problem with USB, see for example:
- https://unity.neuraldsp.com/t/quad-cortex-development-update-46-coros-3-0-0-and-pcom/13696/96
- https://unity.neuraldsp.com/t/quad-cortex-is-corrupting-audio-on-usb-record-on-all-3-devices-2-laptops-1-desktop/13361/26
When the QC is used as a sound card to record audio, the recorded track has randomly a robotic sound. It is extremely annoying, and it seems like neural dsp will not fix it. 

Have you also observed such a behavior?
Do you think the problem can be fixed by patching a few files on the sdcard? 
Do you know what files are responsible for handling the USB connection to the computer?

Thanks!

**Comment by VanIseghemThomas** [comment]
Actually had the exact same issue months into ownership of the QC. I had to RMA it and get a new one (or repaired, not sure) from NDSP. Looks like it is a hardware problem. I would love to tell you what is wrong with it but they never communicated what exactly the issue was, but I'm pretty sure that it is not software related since all units just run the same software.

After sending it to them and getting the unit back I had no problems anymore (except for a very specific situation where it derps out on boot while connecting the wrong things to it). The QC does not seem to have the most reliable hardware unfortunately.

**Comment by scemama** [comment]
OK, thanks a lot for your answer! I was convinced it was a software issue... I will try to have it changed then.
